version: "2"

services:

  mountebank:
    build: docker/mountebank
    ports:
      - 2525:2525
      - 8181:8181
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  prometheus-blackbox:
    build: docker/prometheus-blackbox
    ports:
      - 9115:9115
    links:
      - mountebank
    command:
      blackbox_exporter --config.file=/etc/prometheus/blackbox-exporter.yml
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  prometheus:
    build: docker/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus-data
    links:
      - prometheus-blackbox
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  grafana:
    build: docker/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    #environment:
    #  - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

volumes:

  prometheus-data: {}
  grafana-data: {}
