version: "2"

services:

  mountebank:
    build: docker/mountebank
    ports:
      - 2525:2525
      - 8181:8181
    volumes:
      - ./config/mountebank:/etc/mountebank
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  prometheus-blackbox:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    volumes:
      - ./config/prometheus:/etc/prometheus
    links:
      - mountebank
    command:
      --config.file=/etc/prometheus/blackbox-exporter.yml
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus-data
    links:
      - prometheus-blackbox
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      #- ./config/grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    #environment:
    #  - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

volumes:

  prometheus-data: {}
  grafana-data: {}
