apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mountebank
  name: mountebank
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mountebank
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
