apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --provider openshift --build
      build-config --build-repo https://github.com/MartinSoto/PrometheusExample.git
    kompose.version: 1.9.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: prometheus:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: docker/prometheus/
    git:
      ref: master
      uri: https://github.com/MartinSoto/PrometheusExample.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
